/** Every piece of text the page shows, in one place. */
export const TEXT = {
  title: "MDTP",
  story: "One name, two guarantees: signed in private, published in public.",
  subtitle:
    "An ENS name decides who may write. Sign a file to catch any forgery, or publish it to Sepolia where nobody can forge or delete it.",
  signTab: "Sign",
  publishTab: "Publish",
  readTab: "Read",
  specTab: "Spec",
  connectWallet: "Connect wallet",
  switchToSepolia: "Switch to Sepolia",
  walletFailed: "The wallet request was cancelled or failed.",
  noWallet:
    "No browser wallet found. Verifying still works; signing and managing members need one.",
  getMetaMask: "Get MetaMask",
  rpcUrlLabel: "Sepolia RPC URL",
  parentNameLabel: "Parent ENS name",
  parentNameHint: "Members are subnames of this name.",
  fileLabel: "Markdown file",
  openFile: "Open file",
  filePlaceholder: "Drop a .md file here, open one, or type Markdown.",
  checking: "Checking",
  checkingDetail: "Verifying the signature against ENS.",
  verified: "Verified",
  verifiedDetail: (signer: string): string => `Signed by ${signer}`,
  tampered: "Tampered",
  tamperedDetail: (signer: string): string =>
    `The body or key no longer matches ${signer}`,
  unauthorized: "Unauthorized",
  unauthorizedDetail: (signer: string, reason: string): string =>
    `${signer} may not sign now: ${reason}`,
  unsigned: "Unsigned",
  unsignedDetail: "This file carries no signature.",
  unreachable: "Not checked",
  unreachableDetail: "The Sepolia RPC endpoint did not answer.",
  signerLabel: "Sign as",
  signerPlaceholder: "bob.mdsig91205.eth",
  sign: "Sign with wallet",
  download: "Download signed file",
  noWalletHint: "Install MetaMask or another browser wallet to sign.",
  signFailed: "Signing was cancelled or failed.",
  permissions: "Permissions",
  parentName: (parentName: string): string => `Members of ${parentName}`,
  noMembers: "No members yet.",
  granted: "Granted",
  revoked: "Revoked",
  pending: "Pending",
  grant: "Grant",
  revoke: "Revoke",
  memberLabel: "Member label",
  memberLabelPlaceholder: "carol",
  memberAddress: "Member address",
  memberAddressPlaceholder: "0x...",
  waitingForWallet: "Waiting for the wallet",
  waitingForConfirmation: "Waiting for confirmation",
  viewTransaction: "View transaction on Etherscan",
  transactionFailed: "The transaction was cancelled or failed.",
  connectToManage: (parentName: string): string =>
    `Connect the wallet that owns ${parentName}, or one holding roles on its registry, to grant or revoke.`,
  switchToManage: "Switch the wallet to Sepolia to grant or revoke.",
  parentUnowned: (parentName: string): string =>
    `${parentName} has no owner on Sepolia, so nobody can grant for it.`,
  cannotGrantOrRevoke: (parentName: string, owner: string): string =>
    `This wallet is not ${parentName}'s owner ${owner} and lacks ROLE_REGISTRAR and ROLE_UNREGISTER on its registry, so it cannot grant or revoke.`,
  cannotGrant: (parentName: string): string =>
    `This wallet lacks ROLE_REGISTRAR on ${parentName}'s registry, so it cannot grant.`,
  cannotRevoke: (parentName: string): string =>
    `This wallet lacks ROLE_UNREGISTER on ${parentName}'s registry, so it cannot revoke.`,
  loadingMembers: "Reading members from Sepolia",
  ownedBy: "Owned by",
  noOwner: "No owner; it cannot sign",
  loadFailed: "Could not read the members from Sepolia.",
  teamTitle: "Create a team name",
  teamSubtitle:
    "Register your own .eth name on Sepolia, with its own registry for members. Test USDC pays for it.",
  teamLabel: "Team name",
  teamLabelPlaceholder: "myteam",
  teamCheck: "Check",
  teamCreate: "Create team name",
  teamConnect: "Connect a wallet on Sepolia with some test ETH to create one.",
  teamAvailable: (name: string): string => `${name} is available.`,
  teamTaken: (name: string): string => `${name} is taken; try another.`,
  teamCheckFailed: "Could not check the name on Sepolia.",
  teamSteps: {
    deployRegistry: "Deploy the members registry",
    deployResolver: "Deploy the resolver",
    mint: "Mint test USDC",
    approve: "Let the registrar spend it",
    commit: "Commit to the name",
    wait: "Wait out the commitment",
    register: "Register the name",
    setAddress: "Point the name at your address",
  },
  teamWaitSeconds: (seconds: number): string => `${seconds} s left`,
  teamFailed:
    "A step was cancelled or failed. Check the name again and start over.",
  teamCreated: (name: string): string =>
    `${name} is yours. The page now shows its members.`,
  readLabel: "Published name",
  readPlaceholder: "mdtp://skills.mdsig91205.eth",
  readHint:
    "Reading needs no wallet: the name's mdtp record points at the transaction that holds the file.",
  read: "Read",
  readExample: "Try",
  reading: (name: string): string => `Reading ${name} from Sepolia`,
  notFound: "Not found",
  notFoundDetail: (name: string): string =>
    `${name} has no published document.`,
  publishedDetail: (publisher: string): string => `Published by ${publisher}`,
  publishedTamperedDetail:
    "The record or its transaction is not an MDTP document.",
  publishedUnauthorizedDetail: (publisher: string, name: string): string =>
    `${publisher} may not publish ${name} now.`,
  publisherLabel: "Publisher",
  publishedAtLabel: "Published",
  transactionLabel: "Transaction",
  frontmatterLabel: "Frontmatter",
  publishTitle: "Publish to Ethereum",
  publishSubtitle:
    "Two transactions from your wallet: the file itself, sent to your own address, then the document name's mdtp record pointed at it. Nobody can forge or delete it after that.",
  documentNameLabel: "Document name",
  documentNamePlaceholder: "skills.mdsig91205.eth",
  publishAsLabel: "Publish as",
  publisherPlaceholder: "mdsig91205.eth",
  publish: "Publish",
  fileStep: "1. The file, sent to your own address",
  recordStep: "2. The name's mdtp record",
  publishConnect: "Connect a wallet to publish.",
  publishSwitch: "Switch the wallet to Sepolia to publish.",
  publishChecking: "Checking what this wallet may publish",
  publishUnreachable: "The Sepolia RPC endpoint did not answer.",
  publishNotAllowed: (publisher: string, name: string): string =>
    `${publisher} may not publish ${name}. Publish as the name itself, one of its parents, or a member of its parent.`,
  publishNotOwner: (publisher: string): string =>
    `This wallet does not own ${publisher}.`,
  publishNoResolver: (name: string): string =>
    `${name} has no resolver to hold the mdtp record.`,
  publishDenied: (name: string): string =>
    `This wallet may not set the mdtp record of ${name}. The owner of its parent can allow it with authorizeTextRoles.`,
  publishedTitle: "Published",
  publishedShare: "Share this link; anyone can read it without a wallet:",
  copyLink: "Copy link",
};
