/** Every piece of text the page shows, in one place. */
export const TEXT = {
  title: "Markdown ENS Signature",
  subtitle:
    "Sign a Markdown file with an ENS name and verify it against ENSv2 permissions on Sepolia.",
  connectWallet: "Connect wallet",
  switchToSepolia: "Switch to Sepolia",
  walletFailed: "The wallet request was cancelled or failed.",
  noWallet:
    "No browser wallet found. Verifying still works; signing and managing members need one.",
  getMetaMask: "Get MetaMask",
  rpcUrlLabel: "Sepolia RPC URL",
  parentNameLabel: "Parent ENS name",
  parentNameHint: "Members are subnames of this name.",
  fileLabel: "Markdown file",
  openFile: "Open file",
  filePlaceholder: "Drop a .md file here, open one, or type Markdown.",
  checking: "Checking",
  checkingDetail: "Verifying the signature against ENS.",
  verified: "Verified",
  verifiedDetail: (signer: string): string => `Signed by ${signer}`,
  tampered: "Tampered",
  tamperedDetail: (signer: string): string =>
    `The body or key no longer matches ${signer}`,
  unauthorized: "Unauthorized",
  unauthorizedDetail: (signer: string): string =>
    `Signer lost permission: ${signer}`,
  unsigned: "Unsigned",
  unsignedDetail: "This file carries no signature.",
  signerLabel: "Sign as",
  signerPlaceholder: "bob.alice.eth",
  sign: "Sign with wallet",
  download: "Download signed file",
  noWalletHint: "Install MetaMask or another browser wallet to sign.",
  signFailed: "Signing was cancelled or failed.",
  permissions: "Permissions",
  parentName: (parentName: string): string => `Members of ${parentName}`,
  noMembers: "No members yet.",
  granted: "Granted",
  revoked: "Revoked",
  notMember: "Not a member",
  pending: "Pending",
  grant: "Grant",
  revoke: "Revoke",
  waitingForConfirmation: "Waiting for confirmation",
  viewTransaction: "View transaction on Etherscan",
  transactionFailed: "The transaction was cancelled or failed.",
  newMemberLabel: "Add a member",
  newMemberPlaceholder: "carol",
  addMember: "Add",
  loadFailed: "Could not read the members.",
};
