/** Every piece of text the page shows, in one place. */
export const TEXT = {
  title: "Markdown ENS Signature",
  subtitle:
    "Sign a Markdown file with an ENS name and verify it against ENSv2 permissions on Sepolia.",
  connectWallet: "Connect wallet",
  switchToSepolia: "Switch to Sepolia",
  walletFailed: "The wallet request was cancelled or failed.",
  noWallet:
    "No browser wallet found. Verifying still works; signing and managing members need one.",
  getMetaMask: "Get MetaMask",
  rpcUrlLabel: "Sepolia RPC URL",
  parentNameLabel: "Parent ENS name",
  parentNameHint: "Members are subnames of this name.",
  fileLabel: "Markdown file",
  openFile: "Open file",
  filePlaceholder: "Drop a .md file here, open one, or type Markdown.",
  checking: "Checking",
  checkingDetail: "Verifying the signature against ENS.",
  verified: "Verified",
  verifiedDetail: (signer: string): string => `Signed by ${signer}`,
  tampered: "Tampered",
  tamperedDetail: (signer: string): string =>
    `The body or key no longer matches ${signer}`,
  unauthorized: "Unauthorized",
  unauthorizedDetail: (signer: string, reason: string): string =>
    `${signer} may not sign now: ${reason}`,
  unsigned: "Unsigned",
  unsignedDetail: "This file carries no signature.",
  unreachable: "Not checked",
  unreachableDetail: "The Sepolia RPC endpoint did not answer.",
  signerLabel: "Sign as",
  signerPlaceholder: "bob.mdsig91205.eth",
  sign: "Sign with wallet",
  download: "Download signed file",
  noWalletHint: "Install MetaMask or another browser wallet to sign.",
  signFailed: "Signing was cancelled or failed.",
  permissions: "Permissions",
  parentName: (parentName: string): string => `Members of ${parentName}`,
  noMembers: "No members yet.",
  granted: "Granted",
  revoked: "Revoked",
  pending: "Pending",
  grant: "Grant",
  revoke: "Revoke",
  memberLabel: "Member label",
  memberLabelPlaceholder: "carol",
  memberAddress: "Member address",
  memberAddressPlaceholder: "0x...",
  waitingForWallet: "Waiting for the wallet",
  waitingForConfirmation: "Waiting for confirmation",
  viewTransaction: "View transaction on Etherscan",
  transactionFailed: "The transaction was cancelled or failed.",
  connectToManage: (parentName: string): string =>
    `Connect the wallet that owns ${parentName} to grant or revoke.`,
  switchToManage: "Switch the wallet to Sepolia to grant or revoke.",
  parentUnowned: (parentName: string): string =>
    `${parentName} has no owner on Sepolia, so nobody can grant for it.`,
  notParentOwner: (parentName: string, owner: string): string =>
    `Only ${parentName}'s owner ${owner} can grant or revoke.`,
  loadingMembers: "Reading members from Sepolia",
  ownedBy: "Owned by",
  noOwner: "No owner; it cannot sign",
  loadFailed: "Could not read the members from Sepolia.",
  teamTitle: "Create a team name",
  teamSubtitle:
    "Register your own .eth name on Sepolia, with its own registry for members. Test USDC pays for it.",
  teamLabel: "Team name",
  teamLabelPlaceholder: "myteam",
  teamCheck: "Check",
  teamCreate: "Create team name",
  teamConnect: "Connect a wallet on Sepolia with some test ETH to create one.",
  teamAvailable: (name: string): string => `${name} is available.`,
  teamTaken: (name: string): string => `${name} is taken; try another.`,
  teamCheckFailed: "Could not check the name on Sepolia.",
  teamSteps: {
    deployRegistry: "Deploy the members registry",
    deployResolver: "Deploy the resolver",
    mint: "Mint test USDC",
    approve: "Let the registrar spend it",
    commit: "Commit to the name",
    wait: "Wait out the commitment",
    register: "Register the name",
    setAddress: "Point the name at your address",
  },
  teamWaitSeconds: (seconds: number): string => `${seconds} s left`,
  teamFailed:
    "A step was cancelled or failed. Check the name again and start over.",
  teamCreated: (name: string): string =>
    `${name} is yours. The page now shows its members.`,
};
